#!/bin/sh
# Unless explicitly acquired and licensed from Licensor under another license, the contents of this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent versions as allowed by the RPL, and You may not copy or use this file in either source code or executable form, except in compliance with the terms and conditions of the RPL.
#
# All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language governing rights and limitations under the RPL.

: "${FACTORY_ROOT:?FACTORY_ROOT must point to the repository root}"
. "${FACTORY_VERSIONS_FILE:-$FACTORY_ROOT/deploy/local/versions.env}"

FACTORY_ENVBUILDER_IMAGE=${FACTORY_ENVBUILDER_IMAGE:-ghcr.io/coder/envbuilder@sha256:$CODER_ENVBUILDER_DIGEST}
FACTORY_CLONE_IMAGE=${FACTORY_CLONE_IMAGE:-docker.io/alpine/git@sha256:c0280cf9572316299b08544065d3bf35db65043d5e3963982ec50647d2746e26}
FACTORY_CODER_IMAGE=${FACTORY_CODER_IMAGE:-ghcr.io/coder/coder@sha256:$CODER_SERVER_DIGEST}
FACTORY_CODER_AGENT_URL=${FACTORY_CODER_AGENT_URL:-http://coder.coder.svc.cluster.local}
FACTORY_CODER_PUBLIC_URL=${FACTORY_CODER_PUBLIC_URL:-http://coder.localhost}
FACTORY_CODER_WILDCARD_ACCESS_URL=${FACTORY_CODER_WILDCARD_ACCESS_URL:-http://*.apps.coder.localhost}
FACTORY_WORKSPACE_STORAGE_CLASS=${FACTORY_WORKSPACE_STORAGE_CLASS:-}
FACTORY_SOURCE_VOLUME_SIZE=${FACTORY_SOURCE_VOLUME_SIZE:-8Gi}
FACTORY_CLONE_GIT_SECRET=${FACTORY_CLONE_GIT_SECRET:-factory-forgejo-clone}
FACTORY_GIT_CA_SECRET=${FACTORY_GIT_CA_SECRET:-factory-ca}
FACTORY_ENVBUILDER_CACHE_REPO=${FACTORY_ENVBUILDER_CACHE_REPO:-}
FACTORY_ENVBUILDER_CACHE_PULL_SECRET=${FACTORY_ENVBUILDER_CACHE_PULL_SECRET:-}
FACTORY_ENVBUILDER_CACHE_PUSH_SECRET=${FACTORY_ENVBUILDER_CACHE_PUSH_SECRET:-}
FACTORY_STAGING_POPULATES_CACHE=${FACTORY_STAGING_POPULATES_CACHE:-false}
FACTORY_CODER_VERIFICATION_OWNER=${FACTORY_CODER_VERIFICATION_OWNER:-factory-verification}
FACTORY_CODER_STAGING_OWNER=${FACTORY_CODER_STAGING_OWNER:-factory-stage}
FACTORY_CODER_RESTRICTED_APP_SHARING=${FACTORY_CODER_RESTRICTED_APP_SHARING:-authenticated}
export FACTORY_ENVBUILDER_IMAGE FACTORY_CLONE_IMAGE FACTORY_CODER_IMAGE
export FACTORY_CODER_AGENT_URL FACTORY_CODER_PUBLIC_URL FACTORY_CODER_WILDCARD_ACCESS_URL
export FACTORY_WORKSPACE_STORAGE_CLASS FACTORY_SOURCE_VOLUME_SIZE FACTORY_CLONE_GIT_SECRET FACTORY_GIT_CA_SECRET
export FACTORY_ENVBUILDER_CACHE_REPO FACTORY_ENVBUILDER_CACHE_PULL_SECRET FACTORY_ENVBUILDER_CACHE_PUSH_SECRET
export FACTORY_STAGING_POPULATES_CACHE FACTORY_CODER_VERIFICATION_OWNER FACTORY_CODER_STAGING_OWNER FACTORY_CODER_RESTRICTED_APP_SHARING
