/*
 * Unless explicitly acquired and licensed from Licensor under another license, the contents of this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent versions as allowed by the RPL, and You may not copy or use this file in either source code or executable form, except in compliance with the terms and conditions of the RPL.
 *
 * All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language governing rights and limitations under the RPL.
 */

import { toOpenAPISchema } from '@elysiajs/openapi';
import { createHash } from 'node:crypto';
import { factoryApiRoutes } from './factory-api-routes';
import type { InterviewOperationReconciler } from './interview-operations';
import type { ServerServices } from './types';

type JsonSchema = Record<string, unknown>;
type MediaType = { schema?: JsonSchema };
type Content = Record<string, MediaType>;
type OpenApiResponse = { content?: Content };
type OpenApiOperation = {
  operationId?: string;
  requestBody?: { content?: Content; required?: boolean };
  responses?: Record<string, OpenApiResponse>;
};
type OpenApiDocument = {
  paths: Record<string, Record<string, OpenApiOperation>>;
  components?: {
    schemas?: Record<string, JsonSchema>;
    securitySchemes?: Record<string, Record<string, unknown>>;
  };
  security?: Array<Record<string, string[]>>;
};

const httpMethods = new Set(['delete', 'get', 'head', 'options', 'patch', 'post', 'put', 'trace']);

const inertInterviewOperations: InterviewOperationReconciler = {
  schedule: () => undefined,
  reconcile: async () => undefined,
};

export function buildFactoryOpenApiDocument() {
  const app = factoryApiRoutes(
    {} as ServerServices,
    inertInterviewOperations,
    () => undefined,
  );
  const schema = toOpenAPISchema(app, undefined, undefined, undefined, '3.1.0') as unknown as OpenApiDocument;
  for (const path of Object.values(schema.paths)) {
    for (const operation of Object.values(path)) {
      if (typeof operation.operationId === 'string') operation.operationId = normalizeOperationId(operation.operationId);
    }
  }
  compactSchemas(schema);
  schema.components = {
    ...schema.components,
    securitySchemes: {
      cookieAuth: { type: 'apiKey', in: 'cookie', name: 'factory.session_token' },
    },
  };
  schema.security = [{ cookieAuth: [] }];

  return {
    openapi: '3.1.0',
    info: {
      title: 'Agentic Software Factory API',
      version: '1.0.0',
      description: 'Generated from the Factory Elysia /api/v1 route plugins. Do not edit this file directly.',
    },
    ...schema,
  };
}

function compactSchemas(document: OpenApiDocument): void {
  const schemas: Record<string, JsonSchema> = {};
  const namesBySchema = new Map<string, string>();

  const reference = (schema: JsonSchema, preferredName: string): JsonSchema => {
    const compact = removeSchemaDialects(schema) as JsonSchema;
    const canonical = JSON.stringify(sortRecursively(compact));
    const existingName = namesBySchema.get(canonical);
    if (existingName) return { $ref: `#/components/schemas/${existingName}` };

    let name = preferredName;
    if (schemas[name]) name = `${preferredName}_${createHash('sha256').update(canonical).digest('hex').slice(0, 8)}`;
    schemas[name] = compact;
    namesBySchema.set(canonical, name);
    return { $ref: `#/components/schemas/${name}` };
  };

  for (const pathName of Object.keys(document.paths).sort()) {
    const path = document.paths[pathName]!;
    for (const method of Object.keys(path).sort()) {
      if (!httpMethods.has(method)) continue;
      const operation = path[method]!;
      const operationName = upperFirst(operation.operationId ?? `${method}-${pathName}`)
        .replace(/[^A-Za-z0-9]/g, '');

      if (operation.operationId === 'postApiV1UsersByIdDeprovision' && operation.requestBody) {
        operation.requestBody.required = false;
      }

      const jsonRequest = operation.requestBody?.content?.['application/json'];
      if (operation.requestBody?.content && jsonRequest) {
        operation.requestBody.content = { 'application/json': jsonRequest };
        if (jsonRequest.schema) jsonRequest.schema = reference(jsonRequest.schema, `${operationName}Request`);
      }

      for (const [status, response] of Object.entries(operation.responses ?? {})) {
        if (status === '204' || (response.content as Record<string, unknown> | undefined)?.type === 'void') {
          delete response.content;
          continue;
        }
        const mediaType = response.content?.['application/json'];
        if (!mediaType?.schema) continue;
        const name = Number(status) >= 400 ? 'ErrorResponse' : `${operationName}${status}Response`;
        mediaType.schema = reference(mediaType.schema, name);
      }
    }
  }

  deduplicateNestedSchemas(schemas);
  document.components = { ...document.components, schemas };
}

function deduplicateNestedSchemas(schemas: Record<string, JsonSchema>): void {
  const occurrences = new Map<string, number>();
  const rootNames = new Map<string, string>();
  const roots = Object.entries(schemas).sort(([left], [right]) => left.localeCompare(right));

  for (const [name, schema] of roots) rootNames.set(canonicalSchema(schema), name);
  for (const [, schema] of roots) visitSchemaChildren(schema, (child) => {
    const canonical = canonicalSchema(child);
    occurrences.set(canonical, (occurrences.get(canonical) ?? 0) + 1);
  });

  const rewrite = (schema: JsonSchema): JsonSchema => {
    const rewritten = { ...schema };
    mapSchemaChildren(rewritten, (child) => {
      const canonical = canonicalSchema(child);
      const rootName = rootNames.get(canonical);
      if (rootName) return { $ref: `#/components/schemas/${rootName}` };
      if ((occurrences.get(canonical) ?? 0) < 2 || !isWorthExtracting(child, canonical)) return rewrite(child);

      const name = `Schema_${createHash('sha256').update(canonical).digest('hex').slice(0, 12)}`;
      if (!schemas[name]) schemas[name] = rewrite(child);
      return { $ref: `#/components/schemas/${name}` };
    });
    return rewritten;
  };

  for (const [name, schema] of roots) schemas[name] = rewrite(schema);
}

function canonicalSchema(schema: JsonSchema): string {
  return JSON.stringify(sortRecursively(schema));
}

function isWorthExtracting(schema: JsonSchema, canonical: string): boolean {
  return canonical.length >= 100
    && (schema.type === 'object' || schema.type === 'array' || ['allOf', 'anyOf', 'oneOf'].some((key) => key in schema));
}

function visitSchemaChildren(schema: JsonSchema, visit: (schema: JsonSchema) => void): void {
  mapSchemaChildren(schema, (child) => {
    visit(child);
    visitSchemaChildren(child, visit);
    return child;
  });
}

function mapSchemaChildren(schema: JsonSchema, map: (schema: JsonSchema) => JsonSchema): void {
  for (const key of ['properties', '$defs', 'dependentSchemas']) {
    const children = schema[key];
    if (!children || typeof children !== 'object' || Array.isArray(children)) continue;
    schema[key] = Object.fromEntries(Object.entries(children).map(([name, child]) => [
      name,
      child && typeof child === 'object' && !Array.isArray(child) ? map(child as JsonSchema) : child,
    ]));
  }
  for (const key of ['allOf', 'anyOf', 'oneOf', 'prefixItems']) {
    const children = schema[key];
    if (Array.isArray(children)) {
      schema[key] = children.map((child) => child && typeof child === 'object' && !Array.isArray(child)
        ? map(child as JsonSchema)
        : child);
    }
  }
  for (const key of ['additionalProperties', 'contains', 'else', 'if', 'items', 'not', 'propertyNames', 'then', 'unevaluatedItems', 'unevaluatedProperties']) {
    const child = schema[key];
    if (child && typeof child === 'object' && !Array.isArray(child)) schema[key] = map(child as JsonSchema);
  }
}

function removeSchemaDialects(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(removeSchemaDialects);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => key !== '$schema')
      .map(([key, child]) => [key, removeSchemaDialects(child)]),
  );
}

function upperFirst(value: string): string {
  return value ? `${value[0]!.toUpperCase()}${value.slice(1)}` : 'Schema';
}

function normalizeOperationId(operationId: string): string {
  return operationId.replace(/[^A-Za-z0-9]+([A-Za-z0-9])/g, (_, character: string) => character.toUpperCase());
}

export function serializeFactoryOpenApiDocument(): string {
  return `${JSON.stringify(sortRecursively(buildFactoryOpenApiDocument()), null, 2)}\n`;
}

function sortRecursively(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortRecursively);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, child]) => [key, sortRecursively(child)]),
  );
}
