/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiWorkItemsRouteImport } from './routes/api/work-items'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiWorkItemsIdRouteImport } from './routes/api/work-items/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkItemsRoute = ApiWorkItemsRouteImport.update({
  id: '/api/work-items',
  path: '/api/work-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiWorkItemsIdRoute = ApiWorkItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/work-items': typeof ApiWorkItemsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/work-items/$id': typeof ApiWorkItemsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/work-items': typeof ApiWorkItemsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/work-items/$id': typeof ApiWorkItemsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/work-items': typeof ApiWorkItemsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/work-items/$id': typeof ApiWorkItemsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/config'
    | '/api/health'
    | '/api/me'
    | '/api/work-items'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/work-items/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/config'
    | '/api/health'
    | '/api/me'
    | '/api/work-items'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/work-items/$id'
  id:
    | '__root__'
    | '/'
    | '/api/config'
    | '/api/health'
    | '/api/me'
    | '/api/work-items'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/work-items/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiWorkItemsRoute: typeof ApiWorkItemsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/work-items': {
      id: '/api/work-items'
      path: '/api/work-items'
      fullPath: '/api/work-items'
      preLoaderRoute: typeof ApiWorkItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/work-items/$id': {
      id: '/api/work-items/$id'
      path: '/$id'
      fullPath: '/api/work-items/$id'
      preLoaderRoute: typeof ApiWorkItemsIdRouteImport
      parentRoute: typeof ApiWorkItemsRoute
    }
  }
}

interface ApiHealthRouteChildren {
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

interface ApiWorkItemsRouteChildren {
  ApiWorkItemsIdRoute: typeof ApiWorkItemsIdRoute
}

const ApiWorkItemsRouteChildren: ApiWorkItemsRouteChildren = {
  ApiWorkItemsIdRoute: ApiWorkItemsIdRoute,
}

const ApiWorkItemsRouteWithChildren = ApiWorkItemsRoute._addFileChildren(
  ApiWorkItemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiWorkItemsRoute: ApiWorkItemsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
